name:                hUniversalDB
version:             0.1.0.0
github:              "githubuser/hUniversalDB"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hUniversalDB#readme>

dependencies:
- base >= 4.7 && < 5
- async
- binary
- bytestring
- containers
- data-default
- hslogger
- lens
- MissingH
- mtl
- network-simple
- pretty-show
- random
- stm

library:
  source-dirs: src
  ghc-options:
    - -fwarn-incomplete-patterns

executables:
  hUniversalDB-master-exe:
    main:                Main.hs
    source-dirs:         master
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O0
      - -fwarn-incomplete-patterns
    dependencies:
      - hUniversalDB

  hUniversalDB-slave-exe:
    main:                Main.hs
    source-dirs:         slave
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O0
      - -fwarn-incomplete-patterns
    dependencies:
      - hUniversalDB

  hUniversalDB-client-exe:
    main:                Main.hs
    source-dirs:         client
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O0
      - -fwarn-incomplete-patterns
    dependencies:
      - hUniversalDB

tests:
  hUniversalDB-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0
    - -fwarn-incomplete-patterns
    dependencies:
    - hUniversalDB
